"""Sensor platform for aerosmart."""

from dataclasses import dataclass

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntity,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddConfigEntryEntitiesCallback

from .coordinator import AerosmartConfigEntry
from .entity import AerosmartEntity


@dataclass(frozen=True, kw_only=True)
class AerosmartSensorEntityDescription(SensorEntityDescription):
    """Describes an aerosmart sensor entity."""

    component: str
    attribute: str


SENSOR_DESCRIPTIONS: tuple[AerosmartSensorEntityDescription, ...] = (
    AerosmartSensorEntityDescription(
        key="general_wochentag",
        name="wochentag",
        component="general",
        attribute="wochentag",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="general_software_version",
        name="Software Version",
        component="general",
        attribute="software_version",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="general_device_type",
        name="Gerätetyp",
        component="general",
        attribute="device_type",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="general_revisionstuer",
        name="Revisionstüre",
        component="general",
        attribute="revisionstuer",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="general_time",
        name="Uhrzeit",
        component="general",
        attribute="time",
    ),
    AerosmartSensorEntityDescription(
        key="general_send_date_time",
        name="Uhrzeit und Datum verschicken",
        component="general",
        attribute="send_date_time",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="general_date",
        name="Datum",
        component="general",
        attribute="date",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="outside_temperature_temp_aussenluft",
        name="Temperatur Aussenluft",
        component="outside_temperature",
        attribute="temp_aussenluft",
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="outside_temperature_aussenluft_temp_beschattung",
        name="Temperatur Aussenluft: Beschattung",
        component="outside_temperature",
        attribute="aussenluft_temp_beschattung",
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="outside_temperature_aussenluft_temp_frostschutz",
        name="Temperatur Außenluft: Frostschutz",
        component="outside_temperature",
        attribute="aussenluft_temp_frostschutz",
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="outside_temperature_aussenluft_temp_frostschutz_aus",
        name="Temperatur Außenluft: Frostschutz aus",
        component="outside_temperature",
        attribute="aussenluft_temp_frostschutz_aus",
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="outside_temperature_aussenluft_temp_frostschutz_ein",
        name="Temperatur Außenluft: Frostschutz ein",
        component="outside_temperature",
        attribute="aussenluft_temp_frostschutz_ein",
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="outside_temperature_aussenluft_temp_reduktion_luftmenge_10_percent",
        name="Temperatur Außenluft: Reduktion Luftmenge 10%",
        component="outside_temperature",
        attribute="aussenluft_temp_reduktion_luftmenge_10_percent",
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="outside_temperature_aussenluft_temp_reduktion_luftmenge_20_percent",
        name="Temperatur Außenluft: Reduktion Luftmenge 20%",
        component="outside_temperature",
        attribute="aussenluft_temp_reduktion_luftmenge_20_percent",
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="outside_temperature_aussenluft_temp_sommerautomatik_aktivieren",
        name="Temperatur Außenluft: Sommerautomatik aktivieren",
        component="outside_temperature",
        attribute="aussenluft_temp_sommerautomatik_aktivieren",
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="outside_temperature_aussenluft_temp_sommerautomatik_deaktivieren",
        name="Temperatur Außenluft: Sommerautomatik deaktivieren",
        component="outside_temperature",
        attribute="aussenluft_temp_sommerautomatik_deaktivieren",
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="outside_temperature_aussenluft_temp_sole_nach_aussenluftvorwaermung",
        name="Temperatur: Sole nach Außenluftvorwärmung",
        component="outside_temperature",
        attribute="aussenluft_temp_sole_nach_aussenluftvorwaermung",
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="outside_temperature_aussenluft_temp_schwelle_heizen_kuehlen",
        name="Temperaturschwelle Außenluft \\\\ Heizen / Kühlen",
        component="outside_temperature",
        attribute="aussenluft_temp_schwelle_heizen_kuehlen",
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="outside_temperature_vereisungsschutz",
        name="Vereisungsschutz",
        component="outside_temperature",
        attribute="vereisungsschutz",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="outside_temperature_betriebsstunden_sole_kreis_aussenluft",
        name="Betriebsstunden Solekreis Außenluft",
        component="outside_temperature",
        attribute="betriebsstunden_sole_kreis_aussenluft",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AerosmartSensorEntityDescription(
        key="carbon_dioxide_co2_measurement",
        name="CO2-Messung",
        component="carbon_dioxide",
        attribute="co2_measurement",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="carbon_dioxide_co2",
        name="CO2",
        component="carbon_dioxide",
        attribute="co2",
        native_unit_of_measurement="ppm",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="fine_dust_filter_feinstaubfilter_standzeit",
        name="Feinstaubfilter Standzeit",
        component="fine_dust_filter",
        attribute="feinstaubfilter_standzeit",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="fine_dust_filter_betriebsstunden_feinstaubfilter",
        name="betriebsstunden_feinstaubfilter",
        component="fine_dust_filter",
        attribute="betriebsstunden_feinstaubfilter",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AerosmartSensorEntityDescription(
        key="coarse_dust_filter_betriebsstunden_grobstaubfilter",
        name="betriebsstunden_grobstaubfilter",
        component="coarse_dust_filter",
        attribute="betriebsstunden_grobstaubfilter",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AerosmartSensorEntityDescription(
        key="coarse_dust_filter_grobstaubfilter_standzeit",
        name="Grobstaubfilter Standzeit",
        component="coarse_dust_filter",
        attribute="grobstaubfilter_standzeit",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="coarse_dust_filter_grobstaubfilter_betriebsart_filterueberwachung",
        name="Grobstaubfilter: Betriebsart Filterüberwachung",
        component="coarse_dust_filter",
        attribute="grobstaubfilter_betriebsart_filterueberwachung",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="coarse_dust_filter_grobstaubfilter_max_foerdervolume",
        name="Grobstaubfilter: Maximales Fördervolumen",
        component="coarse_dust_filter",
        attribute="grobstaubfilter_max_foerdervolume",
        native_unit_of_measurement="m³",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="cooling_aussenluft_temp_kuehlung_aus",
        name="Temperatur Außenluft: Kühlung aus",
        component="cooling",
        attribute="aussenluft_temp_kuehlung_aus",
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="cooling_aussenluft_temp_kuehlung_ein",
        name="Temperatur Außenluft: Kühlung ein",
        component="cooling",
        attribute="aussenluft_temp_kuehlung_ein",
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="ventilation_absenkung_aktive_luefterstufe",
        name="Absenkung der Lüfterstufe 1",
        component="ventilation",
        attribute="absenkung_aktive_luefterstufe",
        native_unit_of_measurement="%",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="ventilation_aktive_luefterstufe",
        name="Aktive Lüfterstufe",
        component="ventilation",
        attribute="aktive_luefterstufe",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="ventilation_betriebsart",
        name="Betriebsart",
        component="ventilation",
        attribute="betriebsart",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="ventilation_betriebsstunden_beschattung",
        name="betriebsstunden_beschattung",
        component="ventilation",
        attribute="betriebsstunden_beschattung",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AerosmartSensorEntityDescription(
        key="ventilation_betriebsstunden_frostschutzeinrichtung",
        name="betriebsstunden_frostschutzeinrichtung",
        component="ventilation",
        attribute="betriebsstunden_frostschutzeinrichtung",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AerosmartSensorEntityDescription(
        key="ventilation_betriebsstunden_heizstufe1",
        name="betriebsstunden_heizstufe1",
        component="ventilation",
        attribute="betriebsstunden_heizstufe1",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AerosmartSensorEntityDescription(
        key="ventilation_betriebsstunden_heizstufe2",
        name="betriebsstunden_heizstufe2",
        component="ventilation",
        attribute="betriebsstunden_heizstufe2",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AerosmartSensorEntityDescription(
        key="ventilation_betriebsstunden_luefterstufe0",
        name="betriebsstunden_luefterstufe0",
        component="ventilation",
        attribute="betriebsstunden_luefterstufe0",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AerosmartSensorEntityDescription(
        key="ventilation_betriebsstunden_luefterstufe1",
        name="betriebsstunden_luefterstufe1",
        component="ventilation",
        attribute="betriebsstunden_luefterstufe1",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AerosmartSensorEntityDescription(
        key="ventilation_betriebsstunden_luefterstufe2",
        name="betriebsstunden_luefterstufe2",
        component="ventilation",
        attribute="betriebsstunden_luefterstufe2",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AerosmartSensorEntityDescription(
        key="ventilation_betriebsstunden_luefterstufe3",
        name="betriebsstunden_luefterstufe3",
        component="ventilation",
        attribute="betriebsstunden_luefterstufe3",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AerosmartSensorEntityDescription(
        key="ventilation_beschattungsfunktion",
        name="Beschattungsfunktion",
        component="ventilation",
        attribute="beschattungsfunktion",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="ventilation_befoerderte_kubikmeter",
        name="Gesamt beförderte Kubikmeter",
        component="ventilation",
        attribute="befoerderte_kubikmeter",
        native_unit_of_measurement="m³",
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AerosmartSensorEntityDescription(
        key="ventilation_befoerderte_luftmenge_seit_filterwechsel",
        name="Gesamt beförderte Luftmenge seit Filterwechsel",
        component="ventilation",
        attribute="befoerderte_luftmenge_seit_filterwechsel",
        native_unit_of_measurement="m³",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="ventilation_soll_volumenstrom_abluft",
        name="Soll-Volumenstrom Abluft",
        component="ventilation",
        attribute="soll_volumenstrom_abluft",
        native_unit_of_measurement="m³",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="ventilation_soll_volumenstrom_zuluft",
        name="Soll-Volumenstrom Zuluft",
        component="ventilation",
        attribute="soll_volumenstrom_zuluft",
        native_unit_of_measurement="m³",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="ventilation_volumenstrombalance_zuluftabluft",
        name="Volumenstrombalance ZuluftAbluft",
        component="ventilation",
        attribute="volumenstrombalance_zuluftabluft",
        native_unit_of_measurement="%",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="room_temperature_temp_raumluft",
        name="Temperatur Raumluft",
        component="room_temperature",
        attribute="temp_raumluft",
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="room_temperature_raum_temp_beschattung",
        name="Temperatur Raum Beschattung",
        component="room_temperature",
        attribute="raum_temp_beschattung",
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="summer_bypass_betriebsart_sommerautomatik",
        name="Betriebsart Sommerautomatik",
        component="summer_bypass",
        attribute="betriebsart_sommerautomatik",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="fans_ist_ventilator_zuluft",
        name="ist_ventilator_zuluft",
        component="fans",
        attribute="ist_ventilator_zuluft",
        native_unit_of_measurement="rpm",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="fans_ist_ventilator_abluft",
        name="ist_ventilator_abluft",
        component="fans",
        attribute="ist_ventilator_abluft",
        native_unit_of_measurement="rpm",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="fans_betriebsstunden_abluftventilator",
        name="betriebsstunden_abluftventilator",
        component="fans",
        attribute="betriebsstunden_abluftventilator",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AerosmartSensorEntityDescription(
        key="fans_betriebsstunden_zuluftventilator",
        name="betriebsstunden_zuluftventilator",
        component="fans",
        attribute="betriebsstunden_zuluftventilator",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    AerosmartSensorEntityDescription(
        key="fans_drehzahl_abluftventilator",
        name="Drehzahl Abluftventilator",
        component="fans",
        attribute="drehzahl_abluftventilator",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="fans_drehzahl_zuluftventilator",
        name="Drehzahl Zuluftventilator",
        component="fans",
        attribute="drehzahl_zuluftventilator",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="fans_max_permissible_exhaust_air_fan_speed",
        name="Maximal zulässige Drehzahl Abluftventilator",
        component="fans",
        attribute="max_permissible_exhaust_air_fan_speed",
        native_unit_of_measurement="1/min",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="fans_max_permissible_supply_air_fan_speed",
        name="Maximal zulässige Drehzahl Zuluftventilator",
        component="fans",
        attribute="max_permissible_supply_air_fan_speed",
        native_unit_of_measurement="1/min",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="heat_pump_waermepumpe",
        name="Wärmepumpe",
        component="heat_pump",
        attribute="waermepumpe",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="heat_pump_wp_verdamperregister",
        name="Verdampferregister",
        component="heat_pump",
        attribute="wp_verdamperregister",
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="heat_pump_wp_zentralgeraet_adresse",
        name="Zentralgerät Adresse (WP)",
        component="heat_pump",
        attribute="wp_zentralgeraet_adresse",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="heat_pump_wp_betriebsstunden_kompressormotor",
        name="Betriebsstunden: Kompressormotor",
        component="heat_pump",
        attribute="wp_betriebsstunden_kompressormotor",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="heat_pump_wp_betriebsstunden_magnetventil_fluessiggas",
        name="Betriebsstunden: Magnetventil Flüssiggas",
        component="heat_pump",
        attribute="wp_betriebsstunden_magnetventil_fluessiggas",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="heat_pump_wp_betriebsstunden_magnetventil_heissgas",
        name="Betriebsstunden: Magnetventil Heißgas",
        component="heat_pump",
        attribute="wp_betriebsstunden_magnetventil_heissgas",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="heat_pump_wp_betriebsstunden_magnetventil_luftkondensator",
        name="Betriebsstunden: Magnetventil Luftkondensator",
        component="heat_pump",
        attribute="wp_betriebsstunden_magnetventil_luftkondensator",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="heat_pump_wp_hochdruck",
        name="Hochdruck Wärmepumpe",
        component="heat_pump",
        attribute="wp_hochdruck",
    ),
    AerosmartSensorEntityDescription(
        key="heat_pump_wp_niederdruck",
        name="Niederdruck Wärmepumpe",
        component="heat_pump",
        attribute="wp_niederdruck",
    ),
    AerosmartSensorEntityDescription(
        key="heat_pump_wp_status",
        name="Status Wärmepumpe",
        component="heat_pump",
        attribute="wp_status",
    ),
    AerosmartSensorEntityDescription(
        key="heat_pump_wp_status_restlaufzeit",
        name="Status Wärmepumpe (Restzeit des aktuellen Status)",
        component="heat_pump",
        attribute="wp_status_restlaufzeit",
    ),
    AerosmartSensorEntityDescription(
        key="hot_water_heat_pump_warmwasser_speicher_oben",
        name="Temperatur: Warmwasserspeicher oben (T_BW_EHZ)",
        component="hot_water_heat_pump",
        attribute="warmwasser_speicher_oben",
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="hot_water_heat_pump_warmwasser_warmepumpe",
        name="Temperatur: Warmwasserspeicher Wärmepumpe (T_BW_WP)",
        component="hot_water_heat_pump",
        attribute="warmwasser_warmepumpe",
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="hot_water_heat_pump_ueberschreitung_boilertemp",
        name="Überschreitung Boilertemperatur",
        component="hot_water_heat_pump",
        attribute="ueberschreitung_boilertemp",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="hot_water_heat_pump_wp_vorruebergehende_boilertemperatur",
        name="Vorübergehende Boilerübertemperatur",
        component="hot_water_heat_pump",
        attribute="wp_vorruebergehende_boilertemperatur",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="hot_water_heat_pump_wp_brauchwasser_temp_raumheizungssperre",
        name="Brauchwassertemperatur: Raumheizungssperre",
        component="hot_water_heat_pump",
        attribute="wp_brauchwasser_temp_raumheizungssperre",
        native_unit_of_measurement="°C",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="hot_water_heat_pump_wp_verzoegerung_brauchwasserheizung",
        name="Verzögerung Brauchwassererheizung",
        component="hot_water_heat_pump",
        attribute="wp_verzoegerung_brauchwasserheizung",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    AerosmartSensorEntityDescription(
        key="hot_water_heat_pump_wp_betriebsstunden_elektroheizstab",
        name="Betriebsstunden: Elektroheizstab",
        component="hot_water_heat_pump",
        attribute="wp_betriebsstunden_elektroheizstab",
        native_unit_of_measurement="h",
        device_class=SensorDeviceClass.DURATION,
        state_class=SensorStateClass.MEASUREMENT,
    ),
)


async def async_setup_entry(
    hass: HomeAssistant,
    entry: AerosmartConfigEntry,
    async_add_entities: AddConfigEntryEntitiesCallback,
) -> None:
    """Set up aerosmart sensors."""
    coordinator = entry.runtime_data
    async_add_entities(
        AerosmartSensor(coordinator, description) for description in SENSOR_DESCRIPTIONS
    )


class AerosmartSensor(AerosmartEntity, SensorEntity):
    """An aerosmart sensor entity backed by a single register."""

    entity_description: AerosmartSensorEntityDescription

    @property
    def native_value(self) -> float | int | None:
        """Return the register's current value."""
        return getattr(self._subsystem, self.entity_description.attribute)
